title: CHRÓ¨MA
default_lang: en
author:
  name: 'Kate'
  email: kate@chroma.space
taxonomies:
  - tags
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
menu:
  home:
    url: /
    text: Home
  about:
    url: /about
    text: About
  projects:
    url: /#projects
    text: Projects
  now:
    url: /now
    text: Now
  events:
    url: /events
    text: Events
  contact:
    url: /contact
    text: Contact