enabled: true
dropdown:
  enabled: true
social:
  facebook: 'https://www.facebook.com/chroma.space'
  twitter: 'https://twitter.com/chroma_space'
  github: 'https://github.com/chroma-space'
  mail: hello@chroma.space
quotes:
  -
    quote: 'We re going down to the bottom All the way to the bottom We get turned around There is another world spinning inside of this one.'
    author: 'Laurie Anderson - Free Fall https://www.youtube.com/watch?v=mrD4aWq9Hr4'
  -
    quote: "Don't be your own worst enemy."
    author: 'Bruce Sterling, Literary Freeware -- Not For Commercial Use. Computer Game Developers Conference speech, March 1991: The Wonderful Power of Storytelling https://w2.eff.org/Misc/Publications/Bruce_Sterling/comp_game_designers.article'
  -
    quote: "I now see the Earth realistically as a sphere and think of it as a spaceship."
    author: "Buckminster Fuller, Operating Manual for Spaceship Earth http://72.52.202.216/~fenderse/OperatingManual.html"
  -
    quote: : "The rest of this is more like retooling for World War II, except with everyone playing on the same team."
    author: "Saul Griffith on The Long Now Foundation http://library.fora.tv/2009/01/16/Saul_Griffith_Climate_Change_Recalculated/Griffith_Proposes_Massive_Increase_in_Green_Energy. Reference found via http://worrydream.com/ClimateChange/ "
  -
    quote: : "There are no passengers on Spaceship Earth. We are all crew."
    author: "Marshall McLuhan https://en.wikiquote.org/wiki/Marshall_McLuhan#/media/File:Robot_Arm_Over_Earth_with_Sunburst_-_GPN-2000-001097.jpg See also https://medium.com/poc-stories/we-are-all-crew-68b10a4b0819#.93f0vipb1 http://v2.nl/archive/articles/we-are-all-crew-blowup-reader-4"
